// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACRxYJ1sYv6cbofvs1ohAWPDSsUgb0BrY',
    appId: '1:475989075398:web:b197da4decd4b89dffbec7',
    messagingSenderId: '475989075398',
    projectId: 'claens-5a3e5',
    authDomain: 'claens-5a3e5.firebaseapp.com',
    storageBucket: 'claens-5a3e5.firebasestorage.app',
    measurementId: 'G-4F2LY0MLR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOk5xfJEL7-CzkEmSO4vHGnm1gZN7124',
    appId: '1:475989075398:android:a61009f849e52b5cffbec7',
    messagingSenderId: '475989075398',
    projectId: 'claens-5a3e5',
    storageBucket: 'claens-5a3e5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiaGe2suRI0iLo13hq6SV1O7Q9OEfVd0',
    appId: '1:475989075398:ios:ae8f9f4d0512d0a2ffbec7',
    messagingSenderId: '475989075398',
    projectId: 'claens-5a3e5',
    storageBucket: 'claens-5a3e5.firebasestorage.app',
    iosBundleId: 'com.msubaroda.classlens',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiaGe2suRI0iLo13hq6SV1O7Q9OEfVd0',
    appId: '1:475989075398:ios:a24e2e281d0c2f40ffbec7',
    messagingSenderId: '475989075398',
    projectId: 'claens-5a3e5',
    storageBucket: 'claens-5a3e5.firebasestorage.app',
    iosBundleId: 'com.example.classlens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACRxYJ1sYv6cbofvs1ohAWPDSsUgb0BrY',
    appId: '1:475989075398:web:1ae905a95cebe016ffbec7',
    messagingSenderId: '475989075398',
    projectId: 'claens-5a3e5',
    authDomain: 'claens-5a3e5.firebaseapp.com',
    storageBucket: 'claens-5a3e5.firebasestorage.app',
    measurementId: 'G-YHJKQHHT4L',
  );
}
