// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSO5SXSZCF2StCMdsxQnd7vZgXb_yd2YM',
    appId: '1:548993477348:android:946ceea916948bb2b51af1',
    messagingSenderId: '548993477348',
    projectId: 'claens-f7490',
    storageBucket: 'claens-f7490.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcPSCg1-SH45mgYihELRFC0NiJ8q-39xo',
    appId: '1:548993477348:web:c8c729e587fe0e12b51af1',
    messagingSenderId: '548993477348',
    projectId: 'claens-f7490',
    authDomain: 'claens-f7490.firebaseapp.com',
    storageBucket: 'claens-f7490.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7EIohtAbWqK6aeWhb50kQZJRwzkigTg',
    appId: '1:548993477348:ios:7d56ef152162c8fdb51af1',
    messagingSenderId: '548993477348',
    projectId: 'claens-f7490',
    storageBucket: 'claens-f7490.firebasestorage.app',
    iosBundleId: 'com.example.classlens',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7EIohtAbWqK6aeWhb50kQZJRwzkigTg',
    appId: '1:548993477348:ios:7d56ef152162c8fdb51af1',
    messagingSenderId: '548993477348',
    projectId: 'claens-f7490',
    storageBucket: 'claens-f7490.firebasestorage.app',
    iosBundleId: 'com.example.classlens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcPSCg1-SH45mgYihELRFC0NiJ8q-39xo',
    appId: '1:548993477348:web:28e49af3d6e04e27b51af1',
    messagingSenderId: '548993477348',
    projectId: 'claens-f7490',
    authDomain: 'claens-f7490.firebaseapp.com',
    storageBucket: 'claens-f7490.firebasestorage.app',
  );

}